#!/usr/bin/env bash
# Ping an IP address passed as an argument.
if [ "$#" != 1 ]; then 
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 
fi

# Ping the IP address 5 times
ping -c 5 "$1"
